server.port=8081
spring.application.name=demo

spring.datasource.url=jdbc:postgresql://ep-raspy-waterfall-a1bss4ok-pooler.ap-southeast-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_foJ9TO1HBmgY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud-name=dvg1bkx8s
cloudinary.api-key=737348595539724
cloudinary.api-secret=t1jFiI_9Rl06qibhDQaTcxbnbcg